# Generated by Django 4.2 on 2023-06-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=30)),
                ('cat', models.CharField(max_length=15)),
                ('subcat', models.CharField(max_length=15)),
                ('ret_price', models.IntegerField()),
                ('ws_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WholeSellers',
            fields=[
                ('ip', models.CharField(max_length=18, primary_key=True, serialize=False)),
            ],
        ),
    ]
